[book]
authors = ["忘忧北萱草"]
src = "src"
title = "Git 重学指南"

[output.html]
additional-css = [
    "assets/custom.css",
    "assets/mermaid.css",
]
additional-js = [
    "assets/giscus.js",
    "assets/mermaid.min.js",
    "assets/mermaid-init.js",
]
git-repository-url = "https://github.com/Wybxc/git-remake-guide"
edit-url-template = "https://github.com/Wybxc/git-remake-guide/edit/main/{path}"
sidebar-header-nav = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
